### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by XyloDatapacks** [Nico314159/Retina_v2#1]
in the function retina:traverse/setup in line 14 you have
`execute store result score $int_Z retina.__variable__ run data get entity @s Pos[0] 1`
while it looks like it is supposed to be Pos[2]

Also the block tag #retina:airs should contain "minecraft:light"

**Comment by Nico314159** [comment]
Good catch on both; I kind of forgot light blocks even existed

**Comment by Nico314159** [comment]
Fixed in v2.3.5
